# declare a job name:
#PBS -N genTerraInput
#PBS -l nodes=4:ppn=20
#PBS -l walltime=48:00:00
#PBS -j oe
##PBS -q devel
cd $PBS_O_WORKDIR
module load parallel
module load valgrind

export PARALLEL="--env PATH --env LD_LIBRARY_PATH --env LOADEDMODULES --env _LMFILES_ --env MODULE_VERSION --env MODULEPATH --env MODULEVERSION_STACK --env MODULESHOME"

parallel --jobs $PBS_NUM_PPN --sshloginfile $PBS_NODEFILE --workdir $PBS_O_WORKDIR < genInputFiles1.txt

exit 0
